In [8]:
y=[1,2,3,4]
y.reverse()
print(y)

[4, 3, 2, 1]


In [17]:
import numpy as np
a=np.array(['l','m','n','o','r'])
b=np.array([1,2,3,4,5])
c=a[b==4]
print(c)

['o']


In [40]:
x=['n','z','v','s','t','h','o']
y=x[4]+x[2]
z=x[-3]+x[-5]
print(y)
print(z)

tv
tv


AttributeError: 'list' object has no attribute 'dimensions'

In [58]:
import numpy as np
x = np.array([14, 21,0,0])
y = np.array([12, 6, 23, 29])
w = np.array([5,2,0,0])
z = np.array([x,y,w])
print(z)
print(z.shape)
print(z.size)

[[14 21  0  0]
 [12  6 23 29]
 [ 5  2  0  0]]
(3, 4)
12


In [83]:
z='mathematics'
c=z.count('e')
print(c)

1


In [97]:
a="I said " + ("Hey " * 3) + "Hey!"
print(a)


I said Hey Hey Hey Hey!


In [98]:
a="Hey"+'!'*3 + " my dear friend"
print(a)

Hey!!! my dear friend


In [108]:
print(True + False)

1


In [107]:
a=[1,2,3]
print(type(a))

<class 'list'>


In [3]:
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

areas.append(1)
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 1]


In [32]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
del(areas[10:12])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [38]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
areas1=list(areas)
areas1[1]=11.00
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [95]:
a=[3,5,2,8]
b=["a","w","x","m"]
y=sorted(a,reverse=False)
z=sorted(b,reverse=False)
print(y)
print(z)
for j in b:
    print(j)

[2, 3, 5, 8]
['a', 'm', 'w', 'x']
a
w
x
m


In [86]:
a='prasanth.vattikonda'
l=a.capitalize()
m=a.upper()
n=a.lower()
o=a.count('.')
p=a.replace('a','s')
q=a.index('o')+a.index('s')
print(m)
print(n)
print(l)
print(o)
print(p)
print(q)

PRASANTH.VATTIKONDA
prasanth.vattikonda
Prasanth.vattikonda
1
prsssnth.vsttikonds
18


In [74]:
import math
r=2
c=2*math.pi*r
print('circumference of a circle is '+str(c))
import math
a=math.pi*r**2
print('areas of circle, when radius is 2.1 cm '+ str(a))

circumference of a circle is 12.566370614359172
areas of circle, when radius is 2.1 cm 12.566370614359172


In [85]:
y = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
for i in y:
  print(i)

apple
banana
cherry
orange
kiwi
melon
mango


In [115]:
#Control or conditional  statements  in python if,elif and else
y = {"a","b","c"}
for i in y:
    print(i)
if 'apple' in y:
    print('apple found')
elif 'apple' not in y:
    print('apple not found')
else :
    print('none of the above')

b
a
c
apple not found


In [132]:
y = ["a","b","c"]
y.insert(0,'b')
y.pop(2)
print(y)

['b', 'a', 'c']
